export const SET_ACTIVE_GRADIENT = 'SET_ACTIVE_GRADIENT'
export const CHANGE_GRADIENT = 'CHANGE_GRADIENT'
export const ROTATE_GRADIENT = 'ROTATE_GRADIENT'

export const SET_ACTIVE_PALETTE = 'SET_ACTIVE_PALETTE'

export const USER_DID_LOGIN = 'USER_DID_LOGIN'
export const USER_DID_LOGOUT = 'USER_DID_LOGOUT'
